# Generated by Django 4.1 on 2022-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='/home/hello/Desktop/django_project/media/default.jpg', upload_to='images/'),
        ),
    ]
