# Generated by Django 4.1 on 2022-08-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options_remove_productimages_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
