# Generated by Django 4.1 on 2022-08-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review',
        ),
    ]
