# Generated by Django 4.1 on 2022-08-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
